# Generated by Django 4.2.6 on 2023-10-30 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='video_url',
            field=models.CharField(max_length=200),
        ),
    ]
