# Generated by Django 4.2.6 on 2023-10-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('in progress', 'Progress'), ('finished', 'Finished'), ('not started', 'Default')], default='not started', max_length=11),
        ),
    ]
